#  Version: 0.0.1
FROM fedora
MAINTAINER yyqng <yyqng@qq.com>
ENV UPDATE_TINE 2018-09-26

RUN yum -y install java-1.8.0-openjdk.x86_64
ENV JAVA_HOME /usr/lib/jvm/jre-1.8.0-openjdk-1.8.0.91-0.b14.el7_2.x86_64/
ENV PATH $JAVA_HOME/bin:$PATH
ENV CLASSPATH .:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar

RUN mkdir /home/webapp

RUN yum -y install wget
RUN wget -P /home/webapp/ https://raw.githubusercontent.com/zjm9109/docker/master/1/beyond-center-webapp-0.0.1-SNAPSHOT.jar

ENTRYPOINT [ "java", "-jar", "/home/webapp/beyond-center-webapp-0.0.1-SNAPSHOT.jar" ]

EXPOSE 8080
